### ISSUE TITLE
Upgrade receipt backend to .net 8 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-receipt#213]
### Description

Upgrade solution to .net 8 

### Tasks
- [x] Modify required files
- [x] QA
- [ ] Manual test

### Acceptance Criterias
- [ ] Application targets net8.0
- [ ] Regression tests are successful

**Comment by acn-sbuad** [comment]
verified in at22
