### ISSUE TITLE
Identity and configure necessary accesses for Receipt

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-receipt#264]
### Description
Receipt needs access to Azure resources with workload identity:

- [x] Platform KeyVault
- [ ] Application Insights

### Tasks
- [ ] Configure the necessary accesses through workload identity (helm chart)
    - [ ] Service account (ask @sduranc )
    - [ ] Azure AD configuration?
- [ ] Update the code to no longer use the kvSettings to access the KeyVault
- [ ] Implement a good alternative for when Receipt is running in local dev. 
- [ ] QA
- [ ] Manual tests

### Acceptance criteria
- [ ] Receipt can access the platform key vault without the explicitly shared credentials.
