### ISSUE TITLE
Update material-ui packages to mui/material namespace

### ISSUE THREAD

**Issue by vgr** [Altinn/altinn-receipt#70]
### Description

The current material-ui dependencies in src/frontend is not compatible with the newer versions of React.
altinn-studio has alraedy updated their dependencies to use @mui/material namespace.
Altinn/altinn-studio#9318

### Tasks

- [ ] Change https://github.com/Altinn/altinn-receipt/blob/main/src/frontend/package.json#L16 to `@mui/material`
- [ ] Check that the `yarn.lock` file is referring to the new modules.
- [ ] Replace all usage of `import { X } from '@material-ui/X';`

_No response_

### Acceptance Criterias

- [ ] All usage of material-ui is replaced with mui/material
- [ ] No regressions - local manual tests with app + running unit tests

**Comment by annerisbakk** [comment]
@acn-sbuad Er hele eller deler av denne fremdeles aktuell?

**Comment by acn-sbuad** [comment]
> @acn-sbuad Er hele eller deler av denne fremdeles aktuell?

Don't know. We would need to check with some frontenders.

**Comment by annerisbakk** [comment]
@framitdavid Kan du vurdere denne?

**Comment by framitdavid** [comment]
> @framitdavid Kan du vurdere denne?

Jeg kan ta en vurdering på denne Ila dagen. 🤓

**Comment by framitdavid** [comment]
@annerisbakk hvis du vil ha min objektive mening her, så burde vi ikke bruke tid på å endre dette for alle komponenter som bruker material i dette prosjektet, men heller erstatte material i alle komponenter med `@digdir/designsystemet`. 

Det kan være at noen komponenter ikke kan migreres over til designsystemet fordi designsystemet ikke har en tilsvarende komponent. Her kan man vurdere å fortsette å bruke material enn så lenge, eller om man skal lage sin egen komponent som er en sammenslåing av flere komponenter fra designsystemet for å komme et steg videre.

Jeg ser at det ikke er veldig hyppige commits i frontend her, så usikker på hvem som evt. "eier" prosjektet og har ressurser til å vedlikeholde og gjøre en god opprydding her? Jeg mener hvertfall at det er lite hensiktsmessig å oppdatere material videre, når vi skal over på vårt eget designsystem. 😊

**Comment by annerisbakk** [comment]
@SandGrainOne Høres for meg ut som en sak vi kan lukke, basert på tilbakemelding fra @framitdavid

**Comment by SandGrainOne** [comment]
@annerisbakk Ja, vi kan låse på den versjonen vi har nå, men det kan ikke være slik til all evighet. Noen må en eller annen gang ta den jobben David foreslår.

**Comment by annerisbakk** [comment]
@SandGrainOne Da kan vi lukke denne etter å ha opprettet en ny issue som analyserer jobben beskrevet over.

**Comment by annerisbakk** [comment]
@SandGrainOne Lukker denne og oppfølging gjøres her https://github.com/Altinn/altinn-receipt/issues/242
